# Generated by Django 3.1.5 on 2021-03-06 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealplan', '0002_auto_20210306_0302'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.CharField(choices=[('tomato', 'tomato'), ('mushrooms', 'mushrooms'), ('olives', 'olives')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Intolerances',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intolerance', models.CharField(choices=[('Dairy', 'Dairy'), ('Egg', 'Egg'), ('Gluten', 'Gluten'), ('Grain', 'Grain'), ('Peanut', 'Peanut'), ('Seafood', 'Seafood'), ('Sesame', 'Sesame'), ('Shellfish', 'Shellfish'), ('Soy', 'Soy'), ('Sulfite', 'Sulfite'), ('Tree Nut', 'Tree Nut'), ('Wheat', 'Wheat')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Restrictions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.ManyToManyField(to='mealplan.Ingredients')),
                ('intolerance', models.ManyToManyField(to='mealplan.Intolerances')),
            ],
        ),
        migrations.DeleteModel(
            name='Meal',
        ),
        migrations.DeleteModel(
            name='Member',
        ),
    ]
