# Generated by Django 3.1.5 on 2021-03-06 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealplan', '0004_auto_20210306_0354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='ingredient',
            field=models.CharField(choices=[('tomato', 'Tomato'), ('mushrooms', 'Mushrooms'), ('olives', 'Olives')], max_length=30),
        ),
    ]
