# Generated by Django 3.1.5 on 2021-03-06 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealplan', '0008_auto_20210306_0455'),
    ]

    operations = [
        migrations.AddField(
            model_name='restrictions',
            name='currentdiet',
            field=models.CharField(choices=[('Regular', 'Whole30'), ('Vegetarian', 'Vegetarian'), ('Pescetarian', 'Pescetarian'), ('Vegan', 'Vegan')], default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restrictions',
            name='dietgoal',
            field=models.CharField(choices=[('Regular', 'Whole30'), ('Vegetarian', 'Vegetarian'), ('Pescetarian', 'Pescetarian'), ('Vegan', 'Vegan')], default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restrictions',
            name='level',
            field=models.CharField(choices=[('Trying it out!', 'Trying it out!'), ('Commited to change!', 'Commited to change!'), ('Full on transition!', 'Full on transition')], default=1, max_length=30),
            preserve_default=False,
        ),
    ]
