# Generated by Django 3.1.5 on 2021-03-06 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealplan', '0011_auto_20210306_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restrictions',
            name='dietgoal',
            field=models.CharField(choices=[('Vegetarian', 'Vegetarian'), ('Pescetarian', 'Pescetarian'), ('Vegan', 'Vegan')], max_length=30),
        ),
    ]
