# Generated by Django 3.1.5 on 2021-03-06 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealplan', '0012_auto_20210306_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restrictions',
            name='currentdiet',
            field=models.CharField(choices=[('Regular', 'Regular'), ('Vegetarian', 'Vegetarian'), ('Pescetarian', 'Pescetarian'), ('Vegan', 'Vegan')], default='Regular', max_length=30),
        ),
        migrations.AlterField(
            model_name='restrictions',
            name='dietgoal',
            field=models.CharField(choices=[('Vegetarian', 'Vegetarian'), ('Pescetarian', 'Pescetarian'), ('Vegan', 'Vegan')], default='Vegetarian', max_length=30),
        ),
    ]
