# Generated by Django 3.1.5 on 2021-03-06 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealplan', '0013_auto_20210306_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restrictions',
            name='level',
            field=models.CharField(choices=[('Trying it out!', 'Trying it out!'), ('Commited to change!', 'Commited to change!'), ('Full on transition!', 'Full on transition')], default='Commited to change!', max_length=30),
        ),
    ]
