# Generated by Django 3.1.5 on 2021-03-07 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealplan', '0017_auto_20210307_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restrictions',
            name='ingredient',
            field=models.ManyToManyField(blank=True, to='mealplan.Ingredients'),
        ),
        migrations.AlterField(
            model_name='restrictions',
            name='intolerance',
            field=models.ManyToManyField(blank=True, to='mealplan.Intolerances'),
        ),
    ]
